### ISSUE TITLE
cc1: error: unrecognized command line option "-fno-tree-loop-distribute-patterns"

### ISSUE THREAD

**Issue by djs55** [mirage/mirage-xen-minios#12]
This is on CentOS 6.5 with gcc 4.4.7:
```
$ cc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC)
```

Here's the stdout from `opam install mirage-xen-minios`
```
/install.sh
make[1]: Entering directory `/var/run/sr-mount/88087a1d-af80-a232-ca10-833522abd024/opam/4.01.0/build/mirage-xen-minios.0.6.0/xen-minios-v0.5/extras/mini-os'
ln -sf . include/mini-os
ln -sf ../../../xen/include/public include/xen
ln -sf . arch/x86/include/mini-os
cp /var/run/sr-mount/88087a1d-af80-a232-ca10-833522abd024/opam/4.01.0/build/mirage-xen-minios.0.6.0/xen-minios-v0.5/extras/mini-os/../../xen/include/xen/libfdt/fdt.h include/fdt.h
sed 's!xen/libfdt/!!' /var/run/sr-mount/88087a1d-af80-a232-ca10-833522abd024/opam/4.01.0/build/mirage-xen-minios.0.6.0/xen-minios-v0.5/extras/mini-os/../../xen/include/xen/libfdt/libfdt.h > include/libfdt.h
gcc -DCONFIG_START_NETWORK -DCONFIG_SPARSE_BSS -DCONFIG_BLKFRONT -DCONFIG_NETFRONT -DCONFIG_KBDFRONT -DCONFIG_FBFRONT -DCONFIG_CONSFRONT -DCONFIG_XENBUS -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/4.4.7/include -fno-builtin -Wall -Werror -Wredundant-decls -Wno-format -Wno-redundant-decls -Wformat -fno-stack-protector -fgnu89-inline -Wstrict-prototypes -Wnested-externs -Wpointer-arith -Winline -O3 -fno-tree-loop-distribute-patterns -D__INSIDE_MINIOS__ -m64 -mno-red-zone -fno-reorder-blocks -fno-asynchronous-unwind-tables -isystem /var/run/sr-mount/88087a1d-af80-a232-ca10-833522abd024/opam/4.01.0/build/mirage-xen-minios.0.6.0/xen-minios-v0.5/extras/mini-os/../../extras/mini-os/include -D__MINIOS__ -D__XEN_INTERFACE_VERSION__=0x00030205  -isystem /var/run/sr-mount/88087a1d-af80-a232-ca10-833522abd024/opam/4.01.0/build/mirage-xen-minios.0.6.0/xen-minios-v0.5/extras/mini-os/../../extras/mini-os/arch/x86/include -isystem /var/run/sr-mount/88087a1d-af80-a232-ca10-833522abd024/opam/4.01.0/build/mirage-xen-minios.0.6.0/xen-minios-v0.5/extras/mini-os/../../extras/mini-os/arch/x86/include/x86_64 -c blkfront.c -o /var/run/sr-mount/88087a1d-af80-a232-ca10-833522abd024/opam/4.01.0/build/mirage-xen-minios.0.6.0/xen-minios-v0.5/extras/mini-os/blkfront.o
```
Here's the stderr:
```
+ . ./vars.sh
++ '[' '' = '' ']'
++ command -v opam
+++ opam config var prefix
++ PREFIX=/var/run/sr-mount/88087a1d-af80-a232-ca10-833522abd024/opam/4.01.0
++ MINIOS=minios-v0.5
++ MINIOS_ARCHIVE=minios-v0.5.tar.gz
++ MINIOS_URL=https://github.com/talex5/xen/archive/minios-v0.5.tar.gz
++ LIBM=openlibm-0.4.1-tal1
++ LIBM_ARCHIVE=v0.4.1-tal1.tar.gz
++ LIBM_URL=https://github.com/talex5/openlibm/archive/v0.4.1-tal1.tar.gz
+ rm -rf xen-minios-v0.5
+ tar -zxf minios-v0.5.tar.gz
+ cd xen-minios-v0.5/extras/mini-os
+ make debug=n
cc1: error: unrecognized command line option "-fno-tree-loop-distribute-patterns"
```

**Comment by avsm** [comment]
Is centos 6 support needed, or will just centos 7 be sufficient?

**Comment by djs55** [comment]
I think we can probably target 7 only. I guess the best fix would be to
have a 'configure' step explain the problem and shield the user from the
gcc error.

On Thu, Feb 12, 2015 at 10:51 AM, Anil Madhavapeddy <
notifications@github.com> wrote:

> Is centos 6 support needed, or will just centos 7 be sufficient?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage-xen-minios/issues/12#issuecomment-74051796>
> .
>



-- 
Dave Scott

**Comment by MagnusS** [comment]
I just ran into this problem as well. The flag seems to be defined here: https://github.com/talex5/xen/blob/devel/extras/mini-os/minios.mk#L30

@talex5  do you know if I could just pin and remove the flag as a workaround with gcc 4.4.7 - or is there a better way to solve this?

**Comment by hannesm** [comment]
should most likely be `$(call cc-option,$(CC),-fno-tree-loop-distribute-patterns)` instead...

**Comment by talex5** [comment]
It's probably safe to remove it for very old versions of gcc (since I guess back then we compiled without it). I don't know if there are versions of gcc that support the troublesome optimisation but provide no way to disable it.

The effect of not using the flag when needed is that Mini-OS's `memcpy`, `strlen` and similar basic functions get replaced with versions that directly call themselves, resulting in an infinite loop.

**Comment by avsm** [comment]
I think @hannesm' solution seems safest...

> $(call cc-option,$(CC),-fno-tree-loop-distribute-patterns)

If the flag is present, invoke it.

**Comment by hannesm** [comment]
be aware that this `CFLAGS` reappears in mirage-platform multiple times (https://github.com/mirage/mirage-platform/issues/128), but according to @talex5 (https://github.com/mirage/mirage-platform/issues/124#issuecomment-83449188) can safely be removed from there...

**Comment by hannesm** [comment]
(my last comment: but the CFLAGS in mirage-platform shouldn't matter here due to the check of the minor version of gcc inside the scripts)

**Comment by MagnusS** [comment]
Didn't help much unfortunately. After removing the flag I get this error instead:

```
### stderr ###
# ...[truncated]
# ++ LIBM=openlibm-0.4.1-tal1
# ++ LIBM_ARCHIVE=v0.4.1-tal1.tar.gz
# ++ LIBM_URL=https://github.com/talex5/openlibm/archive/v0.4.1-tal1.tar.gz
# + cp -av /home/mag/git/mirage-xen-minios/xen-minios-v0.6 .
# + cd xen-minios-v0.6/extras/mini-os
# + make debug=n
# In file included from blkfront.c:6:
# /home/mag/.opam/system/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os/../../extras/mini-os/include/stdint.h:1:24: error: stdint-gcc.h: No such file or directory
# make[1]: *** [/home/mag/.opam/system/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os/blkfront.o] Error 1
# make: *** [build] Error 2
```

Looks like stdint-gcc.h isn't available in gcc 4.4...

**Comment by joefiorini** [comment]
> I think we can probably target 7 only.

To the best of my understanding, Xen is not supported on CentOS 7 yet. Seems like this should support 6 at least until there is a simple installation path for Xen on 7. No?

**Comment by avsm** [comment]
@djs55 @jonludlam -- could you comment on CentOS 6 vs 7 and how xen4centos fits into all this?

**Comment by hannesm** [comment]
btw, xen decided to move mini-os out of their xen repository (it [lives here](http://xenbits.xen.org/gitweb/?p=mini-os.git;a=summary)). this does not contain all of our patches to minios, but some updates esp within the build system (esp: it builds with clang, does not depend on stdint-gcc.h anymore, ...)... we should really fork that and getting our patches on top of it (unfortunately I'm currently low on time regarding this). @avsm could you do an automated mirror of the xen mini-os repo within mirage organization on GitHub, similar to (or instead of?) the xen mirror

**Comment by avsm** [comment]
Just confirming that https://github.com/mirage/mini-os <https://github.com/mirage/mini-os> is live and synching upstream.

**Comment by talex5** [comment]
Closing, as the title issue is now fixed. Please open a new issue if compiling on older CentOS versions is still needed and not working for some other reason.
