### ISSUE TITLE
Build fails on platforms without sys/cdefs.h

### ISSUE THREAD

**Issue by justincormack** [mirage/mirage-xen-minios#16]
sys/cdefs.h is a non standard non Posix header and is not available eg under Musl libc, but the openlibm version included here includes it unconditionally, in src/openlibm_complex.h and elsewhere

This is fixed in upstream openlibm, see https://github.com/JuliaLang/openlibm/blob/master/src/cdefs-compat.h

On a Musl libc system build fails with 

```
### stderr ###
# ...[truncated]
#                  from ../src/openlibm.h:20,
#                  from libm-test.c:125,
#                  from test-double.c:34:
# ../src/openlibm_complex.h:21:23: fatal error: sys/cdefs.h: No such file or directory
#  #include <sys/cdefs.h>
#                        ^
# compilation terminated.
# make[2]: *** [test-double] Error 1
```

**Comment by avsm** [comment]
This is still an issue; see 
https://github.com/avsm/opam-pr-build-results/blob/6056/build/log.alpine-3.3_ocaml-4.02.3
in ocaml/opam-repository#6056
