### ISSUE TITLE
build fails on centos6

### ISSUE THREAD

**Issue by avsm** [mirage/mirage-xen-minios#20]
```
# In file included from blkfront.c:6:
# /home/opam/.opam/4.02.3/build/minios-xen.0.9/include/stdint.h:1:24: error: stdint-gcc.h: No such file or directory
# make: *** [/home/opam/.opam/4.02.3/build/minios-xen.0.9/blkfront.o] Error 1
```

Possibly fixed in upstream minios, full build log in https://travis-ci.org/mirage/mirage-xen-minios/jobs/164222117

We will probably just document a minimum of CentOS 7 for Mirage 3.0 unless someone has a quick fix for this...

**Comment by yomimono** [comment]
A minimum of CentOS 7 seems more reasonable than ever now that CentOS 6 is in maintenance mode and nobody's chimed in here to say they need CentOS 6, so I'll close this.
