### ISSUE TITLE
Fails in opam2 sandbox due to no network

### ISSUE THREAD

**Issue by reynir** [mirage/mirage-xen-minios#28]
The package install script uses curl to download libm over the internet. Is it possible to vendor this?

**Comment by reynir** [comment]
Related to #22

**Comment by hannesm** [comment]
that's fixed by https://github.com/ocaml/opam-repository/pull/12444, or am I misguided here?

**Comment by reynir** [comment]
No, you're correct. I forgot Thomas fixed it :-)
